
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.HashMap;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Numan
 */
public class tarifekleme extends javax.swing.JFrame {

    /**
     * Creates new form tarifekleme
     */
    public tarifekleme() {
        initComponents();
        
        hedefmodel = new DefaultTableModel(new Object[]{"MalzemeAdi", "Miktar", "MalzemeBirim"}, 0);
        kullanilacakmalzemelertbl.setModel(hedefmodel);
        
        kaynakmodel = new DefaultTableModel(new Object[]{"MalzemeAdi"}, 0);
        malzemelertbl.setModel(kaynakmodel);
        
        malzemeBirimMap = new HashMap<>();
        
        loadDataFromDatabase();
        
        sayfacombo.setSelectedItem("TARİF EKLE");
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tarifadtf = new javax.swing.JTextField();
        suretf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        talimatta = new javax.swing.JTextArea();
        kategoricb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        kullanilacakmalzemelertbl = new javax.swing.JTable();
        malzemeyisilbtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        malzemelertbl = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        miktartf = new javax.swing.JTextField();
        birimlbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        yenimalzemeadtf = new javax.swing.JTextField();
        yenimalzemebirimcb = new javax.swing.JComboBox<>();
        yenimalzemeeklebtn = new javax.swing.JButton();
        malzemekullanbtn = new javax.swing.JButton();
        sayfacombo = new javax.swing.JComboBox<>();
        yenitarifeklebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("TARİF ADI:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("KATEGORİ:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("HAZIRLANIŞ SÜRESİ:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("YAPILIŞ TALİMATLARI :");

        talimatta.setColumns(20);
        talimatta.setRows(5);
        jScrollPane1.setViewportView(talimatta);

        kategoricb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aperatif", "Çorba", "Et Yemekleri", "İçecek", "Tatlı" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("(DK)");

        kullanilacakmalzemelertbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(kullanilacakmalzemelertbl);

        malzemeyisilbtn.setText("MALZEMEYİ SİL");
        malzemeyisilbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malzemeyisilbtnActionPerformed(evt);
            }
        });

        malzemelertbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        malzemelertbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                malzemelertblMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(malzemelertbl);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("MİKTAR:");

        birimlbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        birimlbl.setText("KG");

        yenimalzemebirimcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADET", "KG", "GRAM", "LİTRE", "ML", "BARDAK", "KAŞIK" }));

        yenimalzemeeklebtn.setText("YENİ MALZEME EKLE");
        yenimalzemeeklebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yenimalzemeeklebtnActionPerformed(evt);
            }
        });

        malzemekullanbtn.setText("EKLE");
        malzemekullanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malzemekullanbtnActionPerformed(evt);
            }
        });

        sayfacombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TARİF LİSTESİ", "TARİF EKLE", "TARİF SİL", "TARİF GÜNCELLE", "MALZEME DÜZENLE" }));
        sayfacombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sayfacomboActionPerformed(evt);
            }
        });

        yenitarifeklebtn.setText("YENİ TARİF EKLE");
        yenitarifeklebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yenitarifeklebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(malzemeyisilbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(suretf, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(tarifadtf)
                                .addComponent(kategoricb, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(yenitarifeklebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(malzemekullanbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(sayfacombo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(miktartf, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(birimlbl)
                                .addGap(13, 13, 13))
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(yenimalzemeadtf, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yenimalzemebirimcb, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yenimalzemeeklebtn, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sayfacombo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(miktartf)
                            .addComponent(birimlbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(malzemekullanbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tarifadtf)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kategoricb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(suretf)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(malzemeyisilbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(yenitarifeklebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yenimalzemebirimcb)
                    .addComponent(yenimalzemeeklebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yenimalzemeadtf, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void malzemekullanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malzemekullanbtnActionPerformed
       
        
        
        int selectedRow = malzemelertbl.getSelectedRow();
        
        
        
        String malzemeAdi = (String) malzemelertbl.getValueAt(selectedRow, 0);
        String malzemeBirim = malzemeBirimMap.get(malzemeAdi); 
        String quantity = miktartf.getText();

        for (int i = 0; i < hedefmodel.getRowCount(); i++) {
            if (hedefmodel.getValueAt(i, 0).equals(malzemeAdi)) {
                JOptionPane.showMessageDialog(this, "Bu malzeme zaten eklenmiş.");
                return; 
            }
        }

        hedefmodel.addRow(new Object[]{malzemeAdi, quantity, malzemeBirim});
        
        miktartf.setText("");
        
    }//GEN-LAST:event_malzemekullanbtnActionPerformed

    private void malzemelertblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_malzemelertblMouseClicked
        int selectedRow = malzemelertbl.getSelectedRow();
        String malzemeAdi = (String) malzemelertbl.getValueAt(selectedRow, 0);
        String malzemeBirim = malzemeBirimMap.get(malzemeAdi); 
        birimlbl.setText(malzemeBirim);
    }//GEN-LAST:event_malzemelertblMouseClicked

    private void malzemeyisilbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malzemeyisilbtnActionPerformed
        int selectedRow = kullanilacakmalzemelertbl.getSelectedRow();
        if (selectedRow != -1) {
            hedefmodel.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(tarifekleme.this, "Lütfen silinecek bir malzeme seçin.");
                }
    }//GEN-LAST:event_malzemeyisilbtnActionPerformed

    private void yenitarifeklebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yenitarifeklebtnActionPerformed
        
        
        String tarifAdi = tarifadtf.getText();
        String kategori = (String) kategoricb.getSelectedItem();
        String hazirlamaSuresi = suretf.getText();
        String talimatlar = talimatta.getText();

        try (Connection conn = DriverManager.getConnection(DB_URL, USER, PASS)) {
            String insertTarifQuery = "INSERT INTO tarifler (TarifAdi, Kategori, HazirlamaSuresi, Talimatlar) VALUES (?, ?, ?, ?)";
            try (PreparedStatement pstmt = conn.prepareStatement(insertTarifQuery, Statement.RETURN_GENERATED_KEYS)) {
                pstmt.setString(1, tarifAdi);
                pstmt.setString(2, kategori);
                pstmt.setInt(3, Integer.parseInt(hazirlamaSuresi));
                pstmt.setString(4, talimatlar);
                pstmt.executeUpdate();

                int tarifId = 0;
                try (ResultSet generatedKeys = pstmt.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        tarifId = generatedKeys.getInt(1); 
                    }
                }

                for (int i = 0; i < hedefmodel.getRowCount(); i++) {
                    String malzemeAdi = (String) hedefmodel.getValueAt(i, 0);
                    String quantity = (String) hedefmodel.getValueAt(i, 1);

                    String getMalzemeIdQuery = "SELECT MalzemeID FROM malzemeler WHERE MalzemeAdi = ?";
                    try (PreparedStatement newpstmt = conn.prepareStatement(getMalzemeIdQuery)) {
                        newpstmt.setString(1, malzemeAdi);
                        try (ResultSet rs = newpstmt.executeQuery()) {
                            if (rs.next()) {
                                int malzemeId = rs.getInt("MalzemeID");
                                String insertTarifMalzemeQuery = "INSERT INTO tarifmalzeme (TarifID, MalzemeID, MalzemeMiktar) VALUES (?, ?, ?)";
                                try (PreparedStatement pstmtInsert = conn.prepareStatement(insertTarifMalzemeQuery)) {
                                    pstmtInsert.setInt(1, tarifId);
                                    pstmtInsert.setInt(2, malzemeId);
                                    pstmtInsert.setString(3, quantity);
                                    pstmtInsert.executeUpdate();
                                }
                            }
                        }
                    }
                }

                JOptionPane.showMessageDialog(this, "Tarif başarıyla kaydedildi.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Tarif kaydetme sırasında hata oluştu: " + e.getMessage());
        }
        
        
        tarifadtf.setText("");
        suretf.setText("");
        talimatta.setText("");
        kategoricb.setSelectedIndex(0);
        hedefmodel.setRowCount(0);
        
        
        
    }//GEN-LAST:event_yenitarifeklebtnActionPerformed

    private void yenimalzemeeklebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yenimalzemeeklebtnActionPerformed
        
        String malzemeAdi = yenimalzemeadtf.getText();
        String malzemeBirim =(String) yenimalzemebirimcb.getSelectedItem();

        try (Connection conn = DriverManager.getConnection(DB_URL, USER, PASS)) {
            String insertMalzemeQuery = "INSERT INTO malzemeler (MalzemeAdi, MalzemeBirim, ToplamMiktar) VALUES (?, ?, ?)";
            try (PreparedStatement pstmt = conn.prepareStatement(insertMalzemeQuery)) {
                pstmt.setString(1, malzemeAdi);
                pstmt.setString(2, malzemeBirim);
                pstmt.setInt(2, 0);
                pstmt.executeUpdate();

                yenimalzemeadtf.setText("");
                yenimalzemebirimcb.setSelectedIndex(0);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Malzeme kaydetme sırasında hata oluştu: " + e.getMessage());
        }
        kaynakmodel.setRowCount(0);
        loadDataFromDatabase();
        
        
        
    }//GEN-LAST:event_yenimalzemeeklebtnActionPerformed

    private void sayfacomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sayfacomboActionPerformed
        if (sayfacombo.getSelectedItem().equals("TARİF LİSTESİ")) {
            new tariflistesi().setVisible(true);
            dispose();
        }
        
        else if (sayfacombo.getSelectedItem().equals("TARİF EKLE")) {
            
            
        }
        
        
        else if (sayfacombo.getSelectedItem().equals("TARİF SİL")) {
            new tarifsilme().setVisible(true);
            dispose();
            
        }
        
        else if (sayfacombo.getSelectedItem().equals("TARİF GÜNCELLE")) {
            new tarifguncelleme().setVisible(true);
            dispose();
        }
        
        else if (sayfacombo.getSelectedItem().equals("MALZEME DÜZENLE")) {
            new malzeme().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_sayfacomboActionPerformed
    
    private static final String DB_URL = "jdbc:mysql://localhost:3306/yemektarif?zeroDateTimeBehavior=CONVERT_TO_NULL";
    private static final String USER = "root";
    private static final String PASS = "1234";
    
    private DefaultTableModel hedefmodel;
    private DefaultTableModel kaynakmodel;
    
    private HashMap<String, String> malzemeBirimMap;
    
    private void loadDataFromDatabase() {
        
        
        try (Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT MalzemeAdi, MalzemeBirim FROM malzemeler")) {

            while (rs.next()) {
                String malzemeAdi = rs.getString("MalzemeAdi");
                String malzemeBirim = rs.getString("MalzemeBirim");
                kaynakmodel.addRow(new Object[]{malzemeAdi}); 
                malzemeBirimMap.put(malzemeAdi, malzemeBirim); 
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Veritabanı bağlantısında hata oluştu: " + e.getMessage());
        }
        
        
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("raven.combobox");
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 13));
        FlatIntelliJLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tarifekleme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birimlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> kategoricb;
    private javax.swing.JTable kullanilacakmalzemelertbl;
    private javax.swing.JButton malzemekullanbtn;
    private javax.swing.JTable malzemelertbl;
    private javax.swing.JButton malzemeyisilbtn;
    private javax.swing.JTextField miktartf;
    private javax.swing.JComboBox<String> sayfacombo;
    private javax.swing.JTextField suretf;
    private javax.swing.JTextArea talimatta;
    private javax.swing.JTextField tarifadtf;
    private javax.swing.JTextField yenimalzemeadtf;
    private javax.swing.JComboBox<String> yenimalzemebirimcb;
    private javax.swing.JButton yenimalzemeeklebtn;
    private javax.swing.JButton yenitarifeklebtn;
    // End of variables declaration//GEN-END:variables
}
